### ISSUE TITLE
Не компилируется на ESP32-S3 с ядром 3.0.0 

### ISSUE THREAD

**Issue by Basoil** [GyverLibs/GyverIO#2]
Не компилируется на ESP32-S3 с ядром 3.0.0 

```
/Users/****/Arduino/libraries/GyverIO/src/gio/gio_esp32.h: In function 'void gio::mode(uint8_t, uint8_t)':
/Users/****/Arduino/libraries/GyverIO/src/gio/gio_esp32.h:34:27: error: 'GPIO' was not declared in this scope
   34 |             if (pin < 32) GPIO.enable_w1tc = (1ul << pin);
      |                           ^~~~
```

upd. Надо добавить #include <soc/gpio_struct.h> в gio_esp32.h

**Comment by GyverLibs** [comment]
странно, а у меня компилится

**Comment by GyverLibs** [comment]
`<soc/gpio_struct.h>` есть на всех есп32, спасибо. Сейчас зарелизю
![image](https://github.com/GyverLibs/GyverIO/assets/84599917/6189a4a0-5ae3-43eb-9fa5-1f17de3b8560)
