### ISSUE TITLE
ESP32(s3) internal pullup/pulldown

### ISSUE THREAD

**Issue by copych** [GyverLibs/GyverIO#5]
Привет, Алекс, 
я так понял, что при наличии внутренней подтяжки используется стандартный набор функций чтения и записи (esp32s3). Это фундаментальное ограничение?

**Comment by GyverLibs** [comment]
Привет, а где ты такое понял?

**Comment by copych** [comment]
В 2 часа ночи мне это показалось очевидным. А теперь я испытываю чувство стыда ))) сорри.
